#!/bin/bash
#SBATCH -J hello           # job name
#SBATCH -o hello.o.%j      # output and error file name (%j expands to jobID)
#SBATCH -e hello.o.%j      # output and error file name (%j expands to jobID)
#SBATCH -n 1               # total number of mpi tasks requested
#SBATCH -N 1               # total number of Nodes requested
#SBATCH -p normal-mic      # queue (partition) -- normal-mic, development, etc.
#SBATCH -t 00:05:00        # run time (hh:mm:ss)


export OMP_NUM_THREADS=1
exoprt MIC_OMP_NUM_THREADS=1

ibrun ./a.out
